### ISSUE TITLE
hat-trie added dependency on Cython

### ISSUE THREAD

**Issue by yakovkeselman** [ceteri/exelixi#1]
After you replaced datrie with hat_trie, cython became a requirement. One idea is to add the dependency, such as "sudo pip install cython" in "bin/local_install.sh". Another idea is to go back to datrie. Thank you.

**Comment by ceteri** [comment]
Many thanks, Yakov!

Resolved by modifying `bin/local_install.sh`,
and hopefully soon the installer gets migrated to "conda" to make these dependencies simpler to manage.
Next on my list :)
